export const ActionTypes = {
  USER_AUNTIFICATED: 'USER_AUNTIFICATED',
  USER_CLICK_DATE: 'USER_CLICK_DATE',
  USER_CLICKED_DATE: 'USER_CLICKED_DATE',
  USER_ADD_EVENT: 'USER_ADD_EVENT',
  USER_INFOS: 'USER_INFOS',
  CALENDAR_INFOS: 'CALENDAR_INFOS',
  HANDLE_HISTORYS: 'HANDLE_HISTORYS',
  ALL_USERS: 'ALL_USERS',
  // REMOVE_SELECTED_PRODUCT: 'REMOVE_SELECTED_PRODUCT',
};
